#!/usr/bin/env bash

TH_REGEX="(th[0-9]|東方紅魔郷|alcostg)"

# Get PID while ensuring one of the games is launched
while [ -z "$TH_PID" ]; do # Loop until a matching process is found
    TH_PID=$(grep -Er "$TH_REGEX" /proc/*/stat | sed "s/.*:\([0-9]\+\).*/\\1/")
    sleep 1
done

# Check if the game is still running
while ps -p $TH_PID > /dev/null; do
    sleep 5
done

# Find and kill the thcrap_loader process
pkill -f "thcrap_loader.exe"
