#!/usr/bin/env bash

# this script is made with bottles in mind, but you can modify it to use it with other launchers
BOTTLES_FOLDER="/home/$USER/.var/app/com.usebottles.bottles"
BOTTLE="Japanese"
THPRAC_LOCATION="/home/$USER/.local/share/thprac/thprac.exe"

RUNNER=$(grep -o 'Runner:.*$' "$BOTTLES_FOLDER/data/bottles/bottles/$BOTTLE/bottle.yml" | sed 's/^Runner: //')
RUNNER_FOLDERS="$BOTTLES_FOLDER/data/bottles/runners"

PROTON_VER="$RUNNER_FOLDERS/$RUNNER/proton"
WINE_VER="$RUNNER_FOLDERS/$RUNNER/bin/wine"

echo "" > '/tmp/thprac_bottles.log'
exec &>>'/tmp/thprac_bottles.log'
exec 2>&1

TH_REGEX="(th[0-9]|東方紅魔郷|alcostg)"

# Get PID while ensuring one of the games is launched
while [ -z "$TH_PID" ]; do # Loop until a matching process is found
    TH_PID=$(grep -Er "$TH_REGEX" /proc/*/stat | sed "s/.*:\([0-9]\+\).*/\\1/")
    sleep 1
done

# Checks if the runner uses proton instead of wine
if [ -f "$PROTON_VER" ]; then
    COMMAND=$(
        echo "'$PROTON_VER' run '$THPRAC_LOCATION'"
    )
else
    COMMAND=$(
        echo "'$WINE_VER' '$THPRAC_LOCATION'"
    )
fi

echo "----------------------LAUNCH THPRAC----------------------"
echo "$COMMAND"
echo "---------------------------------------------------------"

sh -c "$COMMAND" &

# Check if the game is still running
while ps -p $TH_PID > /dev/null; do
    sleep 5
done

# Find and kill the thcrap_loader process
pkill -f "thcrap_loader.exe"

# Find and kill thprac
pkill -f "thprac.exe"
