#!/usr/bin/env bash

THCRAP_FOLDER="/home/$USER/.local/share/thcrap"
THCRAP_CONFIG=en.js
THPRAC_LOCATION="/home/$USER/.local/share/thprac/thprac.exe"

ZENITY=${STEAM_ZENITY:-$(which zenity)}

echo "" > '/tmp/thprac_proton.log'
exec 1<&-
exec 2<&-
exec 1<>'/tmp/thprac_proton.log'
exec 2>&1

launch_config() {
    RUN=$(
        echo "$COMMAND" |
        sed -r "s@ waitforexitandrun.*@ waitforexitandrun '$THCRAP_FOLDER/thcrap.exe' --skip-search-games@"
    )
    sh -c "$RUN"
}

while getopts "k v p c:e:" flag; do
    case "${flag}" in
        k) USE_CUSTOM=1;;
        v) USE_VPATCH=1;;
        p) USE_THPRAC=1;;
        c) THCRAP_CONFIG=${OPTARG};;
        e) COMMAND=${OPTARG};; # Deprecated
    esac
done

if [ -z "$COMMAND" ]; then
    shift "$(($OPTIND -1))"
    COMMAND=''
    # Quote all arguments that contain whitespace
    for i in "$@"; do
        [[ $i =~ ( ) ]] && i=${i@Q}
        COMMAND="$COMMAND $i"
    done
fi

PROTON_VER=$(echo "$COMMAND" | sed -n 's/.*--verb=waitforexitandrun -- \(.*\/proton\).*/\1/p')
ENV_VARIABLES=$(echo "$COMMAND" | sed -r 's/(.* )SteamLaunch.*/\1/' | sed -r 's/(.*)\/home.*/\1/')

echo "---------------------ORIGINAL COMMAND--------------------"
echo "$COMMAND"
echo "---------------------------------------------------------"

if [ ! -f "$THCRAP_FOLDER/thcrap.exe" ]; then
    if ${ZENITY} --question --text="thcrap doesn't appear to be installed on \"$THCRAP_FOLDER\". Would you like this script to install it there?"; then
        mkdir -p "$THCRAP_FOLDER"
        if [ ! -w "$THCRAP_FOLDER" ]; then
            ${ZENITY} --error --text="The directory \"$THCRAP_FOLDER\" could not be created or is not writable. Check your permissions and try again."
            exit
        fi
        LD_LIBRARY_PATH=/usr/lib64:/usr/lib curl -L -f 'https://github.com/thpatch/thcrap/releases/latest/download/thcrap.zip' -o /tmp/thcrap.zip | ${ZENITY} --progress --pulsate --auto-close --text="Downloading thcrap.zip"
        if [ $? != 0 ] || [ ! -f "/tmp/thcrap.zip" ]; then
            ${ZENITY} --error --text="Download failed. Aborting"
            exit
        fi
        if bsdtar -C "$THCRAP_FOLDER" -xf /tmp/thcrap.zip || unzip -d "$THCRAP_FOLDER" /tmp/thcrap.zip; then
            launch_config
        else
            ${ZENITY} --error --text="Failed to extract archive. Make sure you have installed either unzip or bsdtar (libarchive). Aborting"
            exit
        fi
        rm /tmp/thcrap.zip
    fi
fi

if [ ! -f "$THCRAP_FOLDER/config/$THCRAP_CONFIG" ]; then
    CONFIGS=$(ls -Qm "$THCRAP_FOLDER/config" || printf none)
    if ${ZENITY} --question --text="Config file \"$THCRAP_CONFIG\" not found (found: $CONFIGS). Would you like to launch the configuration tool?"; then
        launch_config
    fi
fi

if [ -n "$USE_CUSTOM" ]; then
    SUBCOMMAND=$(echo "$COMMAND" | sed -r 's/(.*waitforexitandrun ).*/\1/')
    GAME_PATH=$(echo "$COMMAND" | sed -r 's/.*waitforexitandrun (.*)/\1/' | sed 's/^\$?\?\('\''\)\?\(.*\)\1\?/\2/' | sed "s/^'//" | sed 's|\(.*\)/.*|\1|')
    COMMAND="${SUBCOMMAND}'${GAME_PATH}/custom.exe'"
elif [ -n "$USE_VPATCH" ]; then
    SUBCOMMAND=$(echo "$COMMAND" | sed -r 's/(.*waitforexitandrun ).*/\1/')
    GAME_PATH=$(echo "$COMMAND" | sed -r 's/.*waitforexitandrun (.*)/\1/' | sed 's/^\$?\?\('\''\)\?\(.*\)\1\?/\2/' | sed "s/^'//" | sed 's|\(.*\)/.*|\1|')
    COMMAND="${SUBCOMMAND}'${GAME_PATH}/vpatch.exe'"
fi

COMMAND=$(
    echo "$COMMAND" |
    sed -r "s@ waitforexitandrun@& '$THCRAP_FOLDER/thcrap_loader.exe' $THCRAP_CONFIG@"
)

echo "--------------------GENERATED COMMAND--------------------"
echo "$COMMAND"
echo "---------------------------------------------------------"

sh -c "$COMMAND" > /dev/null 2>&1 &

if [ -z "$USE_CUSTOM" ]; then
    TH_REGEX="th[0-9].*\.exe"
    ALCOSTG_REGEX="alcostg.*\.exe"
    TH06_REGEX="東方紅魔郷.*"

    # Get PID while ensuring only the actual Touhou executable is chosen
    while [ -z "$TH_PID" ] && [ -z "$ALCOSTG_PID" ] && [ -z "$TH06_PID" ]; do # Loop until a matching process is found
        TH_PID=$(pgrep "$TH_REGEX")
        TH06_PID=$(pgrep "$TH06_REGEX")
        ALCOSTG_PID=$(pgrep "$ALCOSTG_REGEX")
        sleep 1
    done

    if [ -n "$TH06_PID" ]; then
        GAME_PID="$TH06_PID"
    elif [ -n "$ALCOSTG_PID" ]; then
        GAME_PID="$ALCOSTG_PID"
    else
        GAME_PID="$TH_PID"
    fi

    if [ -n "$USE_THPRAC" ]; then
        COMMAND=$(
            echo "$ENV_VARIABLES$PROTON_VER run '$THPRAC_LOCATION'"
        )
        echo "----------------------LAUNCH THPRAC----------------------"
        echo "$COMMAND"
        echo "---------------------------------------------------------"

        sh -c "$COMMAND" > /dev/null 2>&1 &
    fi

    # Check if Touhou is still running
    while ps -f $GAME_PID > /dev/null; do
        sleep 5
    done

    # Find and kill the thcrap_loader process
    pkill -f "thcrap_loader.exe"

    if [ -n "$USE_THPRAC" ]; then
        # Find and kill thprac
        pkill -f "thprac.exe"
    fi
else
    CUSTOM_REGEX="custom.exe"
    
    # Get PID while ensuring only the actual custom executable is chosen
    while [ -z "$CUSTOM_PID" ]; do # Loop until a matching process is found
        CUSTOM_PID=$(pgrep -x "$CUSTOM_REGEX")
        sleep 1
    done

    # Check if custom is still running
    while ps -f $CUSTOM_PID > /dev/null; do
        sleep 5
    done

    # Find and kill the thcrap_loader process
    pkill -f "thcrap_loader.exe"
fi
