#!/usr/bin/env bash

THCRAP_FOLDER="/home/$USER/.local/share/thcrap"
THCRAP_CONFIG=en.js
THPRAC_LOCATION="/home/$USER/.local/share/thprac/thprac.exe"

ZENITY=$(which zenity)

echo "" > '/tmp/thprac_proton.log'
exec &>>'/tmp/thprac_proton.log'
exec 2>&1

launch_config() {
    RUN=$(
        echo "$COMMAND" |
        sed -r "s@ waitforexitandrun.*@ waitforexitandrun '$THCRAP_FOLDER/thcrap.exe' --skip-search-games@"
    )
    sh -c "$RUN"
}

while getopts "d k p v c:" flag; do
    case "${flag}" in
        d) DISABLE_THCRAP=1;;
        k) USE_CUSTOM=1;;
        p) USE_THPRAC=1;;
        v) USE_VPATCH=1;;
        c) THCRAP_CONFIG=${OPTARG};;
    esac
done

if [ -z "$COMMAND" ]; then
    shift "$(($OPTIND -1))"
    COMMAND=''
    # Quote all arguments that contain whitespace
    for i in "$@"; do
        [[ $i =~ ( ) ]] && i=${i@Q}
        COMMAND="$COMMAND $i"
    done
fi

PROTON_VER=$(echo "$COMMAND" | sed -n 's/.*--verb=waitforexitandrun -- \(.*\) waitforexitandrun.*/\1/p')

# Format byte-encoded characters back to text
COMMAND=$(printf "$COMMAND")

echo "---------------------ORIGINAL COMMAND--------------------"
echo "$COMMAND"
echo "---------------------------------------------------------"

if [ ! -f "$THCRAP_FOLDER/thcrap.exe" ]; then
    if ${ZENITY} --question --text="thcrap doesn't appear to be installed on \"$THCRAP_FOLDER\". Would you like this script to install it there?"; then
        mkdir -p "$THCRAP_FOLDER"
        if [ ! -w "$THCRAP_FOLDER" ]; then
            ${ZENITY} --error --text="The directory \"$THCRAP_FOLDER\" could not be created or is not writable. Check your permissions and try again."
            exit
        fi
        LD_LIBRARY_PATH=/usr/lib64:/usr/lib curl -L -f 'https://github.com/thpatch/thcrap/releases/latest/download/thcrap.zip' -o /tmp/thcrap.zip | ${ZENITY} --progress --pulsate --auto-close --text="Downloading thcrap.zip"
        if [ $? != 0 ] || [ ! -f "/tmp/thcrap.zip" ]; then
            ${ZENITY} --error --text="Download failed. Aborting"
            exit
        fi
        if bsdtar -C "$THCRAP_FOLDER" -xf /tmp/thcrap.zip || unzip -d "$THCRAP_FOLDER" /tmp/thcrap.zip; then
            launch_config
        else
            ${ZENITY} --error --text="Failed to extract archive. Make sure you have installed either unzip or bsdtar (libarchive). Aborting"
            exit
        fi
        rm /tmp/thcrap.zip
    fi
fi

if [ ! -f "$THCRAP_FOLDER/config/$THCRAP_CONFIG" ]; then
    CONFIGS=$(ls -Qm "$THCRAP_FOLDER/config" || printf none)
    if ${ZENITY} --question --text="Config file \"$THCRAP_CONFIG\" not found (found: $CONFIGS). Would you like to launch the configuration tool?"; then
        launch_config
    fi
fi

if [ -n "$USE_CUSTOM" ] || [ -n "$USE_THPRAC" ] || [ -n "$USE_VPATCH" ]; then
    SUBCOMMAND=$(echo "$COMMAND" | sed -r 's/(.*waitforexitandrun ).*/\1/')
    GAME_PATH=$(echo "$COMMAND" | sed -r 's/.*waitforexitandrun (.*)/\1/' | sed 's/^\$?\?\('\''\)\?\(.*\)\1\?/\2/' | sed "s/^'//" | sed 's|\(.*\)/.*|\1|')
fi

if [ -n "$USE_CUSTOM" ]; then
    COMMAND="${SUBCOMMAND}'${GAME_PATH}/custom.exe'"
else
    if [ -n "$USE_THPRAC" ]; then
        FOUND_THPRAC=$(find "$GAME_PATH" -maxdepth 1 \( -type f -o -type l \) -exec basename {} \; | grep -E "thprac.*\.exe" | head -n 1)
        if [ -n "$FOUND_THPRAC" ]; then
            COMMAND="${SUBCOMMAND}'${GAME_PATH}/$FOUND_THPRAC'"
        fi
    fi
    if [ -n "$USE_VPATCH" ] && [ -z "$FOUND_THPRAC" ]; then
        COMMAND="${SUBCOMMAND}'${GAME_PATH}/vpatch.exe'"
    fi
fi

if [ -z "$DISABLE_THCRAP" ]; then
    COMMAND=$(
        echo "$COMMAND" |
        sed -r "s@ waitforexitandrun@& '$THCRAP_FOLDER/thcrap_loader.exe' $THCRAP_CONFIG@"
    )
fi

echo "--------------------GENERATED COMMAND--------------------"
echo "$COMMAND"
echo "---------------------------------------------------------"

sh -c "$COMMAND" &

if [ -z "$USE_CUSTOM" ]; then
    TH_REGEX="(th[0-9]|東方紅魔郷|alcostg)"
else
    TH_REGEX="custom"
fi

# Get PID while ensuring one of the games is launched
while [ -z "$TH_PID" ]; do # Loop until a matching process is found
    TH_PID=$(grep -Er "$TH_REGEX" /proc/*/stat | sed "s/.*:\([0-9]\+\).*/\\1/")
    sleep 1
done

if [ -z "$USE_CUSTOM" ] && [ -n "$USE_THPRAC" ] && [ -z "$FOUND_THPRAC" ]; then
    COMMAND="${PROTON_VER} run '${THPRAC_LOCATION}'"
    
    echo "----------------------LAUNCH THPRAC----------------------"
    echo "$COMMAND"
    echo "---------------------------------------------------------"

    sh -c "$COMMAND" &
fi

# Check if the game or custom is still running
while ps -f $TH_PID > /dev/null; do
    sleep 5
done

# Find and kill the thcrap_loader process
pkill -f "thcrap_loader.exe"
